export const getCountryFlag = (country: string): string => {
  const countryFlagMap: Record<string, string> = {
    // Africa
    'Ivory Coast': '🇨🇮',
    'Ghana': '🇬🇭',
    'Ethiopia': '🇪🇹',
    'Algeria': '🇩🇿',
    'Eritrea': '🇪🇷',
    'Mali': '🇲🇱',
    'Central African Republic': '🇨🇫',
    'Gambia': '🇬🇲',
    'Guinea-Bissau': '🇬🇼',
    'Malawi': '🇲🇼',
    'Republic of the Congo': '🇨🇬',
    'Burundi': '🇧🇮',
    'Egypt': '🇪🇬',
    'Morocco': '🇲🇦',
    'Spain': '🇪🇸',
    'Guinea': '🇬🇳',
    'Senegal': '🇸🇳',
    'Tanzania': '🇹🇿',
    'Djibouti': '🇩🇯',
    'Cameroon': '🇨🇲',
    'Western Sahara': '🇪🇭',
    'Sierra Leone': '🇸🇱',
    'Botswana': '🇧🇼',
    'Zimbabwe': '🇿🇼',
    'South Africa': '🇿🇦',
    'South Sudan': '🇸🇸',
    'Uganda': '🇺🇬',
    'Sudan': '🇸🇩',
    'Rwanda': '🇷🇼',
    'Democratic Republic of the Congo': '🇨🇩',
    'Nigeria': '🇳🇬',
    'Gabon': '🇬🇦',
    'Togo': '🇹🇬',
    'Angola': '🇦🇴',
    'Zambia': '🇿🇲',
    'Equatorial Guinea': '🇬🇶',
    'Mozambique': '🇲🇿',
    'Lesotho': '🇱🇸',
    'Eswatini': '🇸🇿',
    'Somalia': '🇸🇴',
    'Liberia': '🇱🇷',
    'Kenya': '🇰🇪',
    'Chad': '🇹🇩',
    'Niger': '🇳🇪',
    'Mauritania': '🇲🇷',
    'Burkina Faso': '🇧🇫',
    'Benin': '🇧🇯',
    'São Tomé and Príncipe': '🇸🇹',
    'Libya': '🇱🇾',
    'Tunisia': '🇹🇳',
    'Namibia': '🇳🇦',

    // America
    'United States': '🇺🇸',
    'Anguilla': '🇦🇮',
    'Antigua and Barbuda': '🇦🇬',
    'Brazil': '🇧🇷',
    'Argentina': '🇦🇷',
    'Aruba': '🇦🇼',
    'Paraguay': '🇵🇾',
    'Canada': '🇨🇦',
    'Mexico': '🇲🇽',
    'Barbados': '🇧🇧',
    'Belize': '🇧🇿',
    'Colombia': '🇨🇴',
    'Venezuela': '🇻🇪',
    'French Guiana': '🇬🇫',
    'Cayman Islands': '🇰🇾',
    'Costa Rica': '🇨🇷',
    'Curaçao': '🇨🇼',
    'Greenland': '🇬🇱',
    'Dominica': '🇩🇲',
    'El Salvador': '🇸🇻',
    'Turks and Caicos Islands': '🇹🇨',
    'Grenada': '🇬🇩',
    'Guadeloupe': '🇬🇵',
    'Guatemala': '🇬🇹',
    'Ecuador': '🇪🇨',
    'Guyana': '🇬🇾',
    'Cuba': '🇨🇺',
    'Jamaica': '🇯🇲',
    'Bonaire, Sint Eustatius and Saba': '🇧🇶',
    'Bolivia': '🇧🇴',
    'Peru': '🇵🇪',
    'Sint Maarten': '🇸🇽',
    'Nicaragua': '🇳🇮',
    'Saint Martin': '🇲🇫',
    'Martinique': '🇲🇶',
    'Saint Pierre and Miquelon': '🇵🇲',
    'Uruguay': '🇺🇾',
    'Montserrat': '🇲🇸',
    'Bahamas': '🇧🇸',
    'Chile': '🇨🇱',
    'Haiti': '🇭🇹',
    'Trinidad and Tobago': '🇹🇹',
    'Puerto Rico': '🇵🇷',
    'Dominican Republic': '🇩🇴',
    'Suriname': '🇸🇷',
    'Saint Barthélemy': '🇧🇱',
    'Saint Kitts and Nevis': '🇰🇳',
    'Saint Lucia': '🇱🇨',
    'U.S. Virgin Islands': '🇻🇮',
    'Saint Vincent and the Grenadines': '🇻🇨',
    'British Virgin Islands': '🇻🇬',

    // Antarctica
    'Antarctica': '🇦🇶',

    // Arctic
    'Svalbard and Jan Mayen': '🇸🇯',

    // Asia
    'Yemen': '🇾🇪',
    'Kazakhstan': '🇰🇿',
    'Jordan': '🇯🇴',
    'Russia': '🇷🇺',
    'Turkmenistan': '🇹🇲',
    'Iraq': '🇮🇶',
    'Bahrain': '🇧🇭',
    'Azerbaijan': '🇦🇿',
    'Thailand': '🇹🇭',
    'Lebanon': '🇱🇧',
    'Kyrgyzstan': '🇰🇬',
    'Brunei': '🇧🇳',
    'Mongolia': '🇲🇳',
    'Sri Lanka': '🇱🇰',
    'Syria': '🇸🇾',
    'Bangladesh': '🇧🇩',
    'East Timor': '🇹🇱',
    'United Arab Emirates': '🇦🇪',
    'Tajikistan': '🇹🇯',
    'Cyprus': '🇨🇾',
    'Palestine': '🇵🇸',
    'Vietnam': '🇻🇳',
    'Hong Kong': '🇭🇰',
    'Indonesia': '🇮🇩',
    'Israel': '🇮🇱',
    'Afghanistan': '🇦🇫',
    'Pakistan': '🇵🇰',
    'Nepal': '🇳🇵',
    'India': '🇮🇳',
    'Malaysia': '🇲🇾',
    'Kuwait': '🇰🇼',
    'Macau': '🇲🇴',
    'Philippines': '🇵🇭',
    'Oman': '🇴🇲',
    'Cambodia': '🇰🇭',
    'North Korea': '🇰🇵',
    'Qatar': '🇶🇦',
    'Uzbekistan': '🇺🇿',
    'Myanmar': '🇲🇲',
    'Saudi Arabia': '🇸🇦',
    'South Korea': '🇰🇷',
    'China': '🇨🇳',
    'Singapore': '🇸🇬',
    'Taiwan': '🇹🇼',
    'Georgia': '🇬🇪',
    'Iran': '🇮🇷',
    'Bhutan': '🇧🇹',
    'Japan': '🇯🇵',
    'Armenia': '🇦🇲',

    // Atlantic
    'Portugal': '🇵🇹',
    'Bermuda': '🇧🇲',
    'Cape Verde': '🇨🇻',
    'Faroe Islands': '🇫🇴',
    'Iceland': '🇮🇸',
    'South Georgia and the South Sandwich Islands': '🇬🇸',
    'Saint Helena': '🇸🇭',
    'Falkland Islands': '🇫🇰',

    // Australia
    'Australia': '🇦🇺',

    // Europe
    'Netherlands': '🇳🇱',
    'Andorra': '🇦🇩',
    'Greece': '🇬🇷',
    'Serbia': '🇷🇸',
    'Germany': '🇩🇪',
    'Slovakia': '🇸🇰',
    'Belgium': '🇧🇪',
    'Romania': '🇷🇴',
    'Hungary': '🇭🇺',
    'Moldova': '🇲🇩',
    'Denmark': '🇩🇰',
    'Ireland': '🇮🇪',
    'Gibraltar': '🇬🇮',
    'Guernsey': '🇬🇬',
    'Finland': '🇫🇮',
    'Isle of Man': '🇮🇲',
    'Turkey': '🇹🇷',
    'Jersey': '🇯🇪',
    'Ukraine': '🇺🇦',
    'Slovenia': '🇸🇮',
    'United Kingdom': '🇬🇧',
    'Luxembourg': '🇱🇺',
    'Malta': '🇲🇹',
    'Åland Islands': '🇦🇽',
    'Belarus': '🇧🇾',
    'Monaco': '🇲🇨',
    'Norway': '🇳🇴',
    'France': '🇫🇷',
    'Montenegro': '🇲🇪',
    'Czech Republic': '🇨🇿',
    'Latvia': '🇱🇻',
    'Italy': '🇮🇹',
    'San Marino': '🇸🇲',
    'Bosnia and Herzegovina': '🇧🇦',
    'North Macedonia': '🇲🇰',
    'Bulgaria': '🇧🇬',
    'Sweden': '🇸🇪',
    'Estonia': '🇪🇪',
    'Albania': '🇦🇱',
    'Liechtenstein': '🇱🇮',
    'Vatican City': '🇻🇦',
    'Austria': '🇦🇹',
    'Lithuania': '🇱🇹',
    'Poland': '🇵🇱',
    'Croatia': '🇭🇷',
    'Switzerland': '🇨🇭',

    // Indian Ocean
    'Madagascar': '🇲🇬',
    'British Indian Ocean Territory': '🇮🇴',
    'Christmas Island': '🇨🇽',
    'Cocos (Keeling) Islands': '🇨🇨',
    'Comoros': '🇰🇲',
    'French Southern Territories': '🇹🇫',
    'Seychelles': '🇸🇨',
    'Maldives': '🇲🇻',
    'Mauritius': '🇲🇺',
    'Mayotte': '🇾🇹',
    'Réunion': '🇷🇪',

    // Pacific
    'Samoa': '🇼🇸',
    'New Zealand': '🇳🇿',
    'Papua New Guinea': '🇵🇬',
    'Federated States of Micronesia': '🇫🇲',
    'Vanuatu': '🇻🇺',
    'Kiribati': '🇰🇮',
    'Tokelau': '🇹🇰',
    'Fiji': '🇫🇯',
    'Tuvalu': '🇹🇻',
    'French Polynesia': '🇵🇫',
    'Solomon Islands': '🇸🇧',
    'Guam': '🇬🇺',
    'Marshall Islands': '🇲🇭',
    'Nauru': '🇳🇷',
    'Niue': '🇳🇺',
    'Norfolk Island': '🇳🇫',
    'New Caledonia': '🇳🇨',
    'American Samoa': '🇦🇸',
    'Palau': '🇵🇼',
    'Pitcairn Islands': '🇵🇳',
    'Cook Islands': '🇨🇰',
    'Northern Mariana Islands': '🇲🇵',
    'Tonga': '🇹🇴',
    'Wallis and Futuna': '🇼🇫',
  };

  return countryFlagMap[country] || '🏳️';
};

export const getCountryFlagImageUrl = (country: string): string => {
  // Alternative approach using country code to construct flag image URLs
  const countryCodeMap: Record<string, string> = {
    'United States': 'us',
    'United Kingdom': 'gb',
    'Japan': 'jp',
    'Germany': 'de',
    'France': 'fr',
    'China': 'cn',
    'India': 'in',
    'Brazil': 'br',
    'Australia': 'au',
    'Canada': 'ca',
    'Russia': 'ru',
    'Italy': 'it',
    'Spain': 'es',
    'Nigeria': 'ng',
    // Add more mappings as needed
  };

  const code = countryCodeMap[country];
  if (code) {
    return `https://flagcdn.com/w80/${code}.png`;
  }
  return '';
};